### ISSUE TITLE
Missing Enum data type in GrahpQL endpoint

### ISSUE THREAD

**Issue by gciavarrini** [apache/incubator-kie-kogito-docs#676]
In [Data Index GraphQL Endpoint](https://sonataflow.org/serverlessworkflow/main/data-index/data-index-core-concepts.html#data-index-graphql) `Enum` data type isn't listed, but it's allowed with `equal` and `in` operators.

**Comment by gciavarrini** [comment]
@ricardozanini after rethinking about this issue, I believe the current fix might not be the best approach because, in truth, there isn't an actual `Enum` type.

Enumerates are defined like:
```yaml
{
  "name": "state",
  "type": {
    "kind": "INPUT_OBJECT",
    "name": "ProcessInstanceStateArgument",
    "ofType": null
    }
}
```
So, the type is represented by the object's name (`ProcessInstanceStateArgument` in this case).
I'm unsure how to best handle the type.

(For reference, here's an example of `IdArgument`
``` yaml
{
  "name": "id",
  "type": {
    "kind": "INPUT_OBJECT",
    "name": "IdArgument",
    "ofType": null
  }
}
```

Any thoughts or suggestions on a better way to address this?
